name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Required for GHCR

    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up image name
      id: image
      run: echo "IMAGE=ghcr.io/${{ github.repository_owner }}/pcap2csv" >> $GITHUB_ENV

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ${IMAGE}:$(date +%s)
        docker build . --file Dockerfile --tag ${IMAGE}:latest

    - name: Push image to GHCR
      run: |
        docker push $IMAGE:$(date +%s)
        docker push $IMAGE:latest
